
CREATE TABLE `USER` (
    `USER_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '유저ID 기본키',
    `NAME` VARCHAR(50) NOT NULL COMMENT '유저 이름',
    `ID` VARCHAR(30) NOT NULL COMMENT '유저 로그인 아이디',
    `PASSWORD` VARCHAR(30) NOT NULL COMMENT '유저 로그인 비밀번호',
    `NICK_NAME` VARCHAR(50) UNIQUE NOT NULL COMMENT '유저 닉네임(중복안됨)' ,
    `BIRTH_DATE` CHAR(8) NOT NULL COMMENT '생일',
    `PHONE` CHAR(11) NOT NULL COMMENT '휴대폰 번호',
    `ADDRESS` VARCHAR(200) NOT NULL COMMENT '주소',
    `ADDRESS_DETAIL` VARCHAR(200) COMMENT '주소 상세',
    `EMAIL` VARCHAR(200) UNIQUE NOT NULL COMMENT '유저 이메일 (중복안됨)',
    `ANIMAL_REG_STATUS` CHAR(1) NOT NULL COMMENT '0: 등록 X, 1: 등록 O',
    `PROFILE_IMAGE_URL` VARCHAR(255) COMMENT '프로필 사진 주소',
    `GENDER` CHAR(1) NOT NULL COMMENT '성별  0: 비공개, 1: 남성, 2: 여성',
    `IS_DELETED` CHAR(1) DEFAULT 1 NOT NULL COMMENT '삭제여부  O: 삭제, 1: 사용',
    `CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    `UPDATE_AT` DATETIME COMMENT '수정 시간'
);

CREATE TABLE `PET_PROFILE` (
    `PET_PROFILE_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '반려동물ID 기본키',
    `USER_ID` int unsigned NOT NULL COMMENT '유저ID',
    `PET_NAME` VARCHAR(200) NOT NULL COMMENT '반려동물 이름',
    `PET_GENDER` CHAR(1) NOT NULL COMMENT '반려동물 성별 0: 중성, 1: 수컷, 2: 암컷',
    `PET_BIRTH_DATE` CHAR(6) NOT NULL COMMENT '반려동물 생일',
    `WEIGHT` SMALLINT NOT NULL COMMENT '반려동물 체중',
    `PET_PROFILE_IMAGE_URL` VARCHAR(255) COMMENT '반려동물 프로필 사진 주소',
    `ADD_INFO` VARCHAR(255) COMMENT '추가 정보',
    `NEUTRALITY_YN` CHAR(1) NOT NULL COMMENT '중성화 여부 0: 중성화 X, 1: 중성화 O',
    `CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    `UPDATE_AT` DATETIME COMMENT '수정 시간',
    FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
);

CREATE TABLE `USER_DEL_LOG` (
    `USER_DEL_LOG_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '삭제로그ID 기본키',
    `USER_ID` int unsigned NOT NULL COMMENT '유저ID',
    `CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
);

CREATE TABLE `INQUERY_AND_REPORT_CATE_CD` (
    `INQUERY_AND_REPORT_CATE_CD_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '문의 및 신고 카테고리ID 기본키',
    `TYPE` CHAR(1) NOT NULL COMMENT '카테고리 1: 문의사항, 2: 신고',
    `CATE_CD_NAME` VARCHAR(30) NOT NULL COMMENT '카테고리 이름'
);

CREATE TABLE `INQUERY_AND_REPORT` (
    `INQUERY_AND_REPORT_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '문의 및 신고ID 기본키',
    `USER_ID` int unsigned NOT NULL COMMENT '유저ID',
    `INQUERY_AND_REPORT_CATE_CD_ID` int unsigned NOT NULL COMMENT '문의 및 신고ID',
    `TITLE` VARCHAR(100) NOT NULL COMMENT '제목',
    `CONTENT` VARCHAR(500) NOT NULL COMMENT '내용',
    `REPORT_USER_ID` INT COMMENT '문의사항일 때는 NULL값 들어감',
    `STATUS` CHAR(1) DEFAULT 0 NOT NULL COMMENT '처리상태  0: 미처리, 1: 처리완료',
    `CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    `UPDATE_AT` DATETIME COMMENT '수정 시간',
    FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`),
    FOREIGN KEY (`INQUERY_AND_REPORT_CATE_CD_ID`) REFERENCES `INQUERY_AND_REPORT_CATE_CD` (`INQUERY_AND_REPORT_CATE_CD_ID`)
);


CREATE TABLE `PROVIDERS` (
    `PROVIDERS_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '댕시터(제공제)ID 기본키',
    `USER_ID` int unsigned NOT NULL COMMENT '유저ID',
    `PROVIDERS_NICK_NAME` VARCHAR(30) NOT NULL COMMENT '댕시터(제공자) 닉네임',
    `INTRODUCTION` VARCHAR(255) NOT NULL COMMENT '댕시터 소개',
    `PROVISION_YN` CHAR(1) DEFAULT 0 NOT NULL COMMENT '영업 여부 0: 영업중지, 1: 영업중',
    `MON` CHAR(1) NOT NULL COMMENT '월요일 0: 영업 X, 1: 영업 O',
    `TUE` CHAR(1) NOT NULL COMMENT '화요일 0: 영업 X, 1: 영업 O',
    `WED` CHAR(1) NOT NULL COMMENT '수요일 0: 영업 X, 1: 영업 O',
    `THU` CHAR(1) NOT NULL COMMENT '목요일 0: 영업 X, 1: 영업 O',
    `FRI` CHAR(1) NOT NULL COMMENT '금요일 0: 영업 X, 1: 영업 O',
    `SAT` CHAR(1) NOT NULL COMMENT '토요일 0: 영업 X, 1: 영업 O',
    `SUN` CHAR(1) NOT NULL COMMENT '일요일 0: 영업 X, 1: 영업 O',
    `PROVISION_OPTION` ENUM('WALK', 'BATH', 'FOOD') NOT NULL COMMENT '산책, 목욕, 밥주기',
    FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
);


CREATE TABLE `RESERVATION_LIST` (
    `RESERVATION_LIST_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '예약목록ID 기본키',
    `USER_ID` int unsigned NOT NULL COMMENT '유저ID',
    `PROVIDERS_ID` int unsigned NOT NULL COMMENT '댕시터(제공자)ID',
    `START_TIME` DATETIME NOT NULL COMMENT '영업 시작 시간',
    `END_TIME` DATETIME NOT NULL COMMENT '영업 종료 시간',
    `CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    `RESERVATION_STATUS` CHAR(1) DEFAULT 0 COMMENT '예약 상태 0: 예약대기, 1: 예약수락(진행중), 2: 예약거절, 3: 예약취소, 4: 완료',
    FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`),
    FOREIGN KEY (`PROVIDERS_ID`) REFERENCES `PROVIDERS` (`PROVIDERS_ID`)
);

CREATE TABLE `REVIEW` (
    `REVIEW_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '리뷰ID 기본키',
    `PROVIDERS_ID` int unsigned NOT NULL COMMENT '댕시터(제공자)ID',
    `USER_ID` int unsigned NOT NULL COMMENT '유저ID',
    `REVIEW_SCORE` SMALLINT NOT NULL COMMENT '별점',
    `REVIEW_CONTENT` VARCHAR(500) NOT NULL COMMENT '리뷰 내용',
    FOREIGN KEY (`PROVIDERS_ID`) REFERENCES `PROVIDERS` (`PROVIDERS_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
);

CREATE TABLE `HEALTH_RECORD` (
    `HEALTH_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '건강기록ID 기본키',
    `PET_PROFILE_ID` int unsigned NOT NULL COMMENT '반려동물ID',
    `WEIGHT` SMALLINT NOT NULL COMMENT '펫 체중',
    `PET_AGE` SMALLINT NOT NULL COMMENT '펫 나이',
    `ABNORMAL_SYMPTOMS` VARCHAR(255) NOT NULL COMMENT '이상 증상',
    `MEDICAL_RECORD` VARCHAR(500) NOT NULL COMMENT '진료 내역',
    `CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    `UPDATE_AT` DATETIME COMMENT '수정 시간',
    `ABNORMAL_SYMPTOMS_IMAGE_URL` VARCHAR(255) COMMENT '이상 증상 사진 URL',
    `MEMO` VARCHAR(255) COMMENT '메모',
    FOREIGN KEY (`PET_PROFILE_ID`) REFERENCES `PET_PROFILE` (`PET_PROFILE_ID`)
);

CREATE TABLE `ACCOUNT_BOOK` (
    `ACCOUNT_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '가계부ID 기본키',
    `USER_ID` int unsigned NOT NULL COMMENT '유저ID',
    `CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    `UPDATE_AT` DATETIME COMMENT '수정 시간',
    `MEMO` VARCHAR(255) NOT NULL COMMENT '메모',
    FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
);

CREATE TABLE `WALKING_RECORD` (
    `WALK_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '산책기록ID 기본키',
    `PET_PROFILE_ID` int unsigned NOT NULL COMMENT '펫ID',
    `WEATHER_STATE` CHAR(1) DEFAULT 0 NOT NULL COMMENT '날씨 상태  0: 맑음, 1: 흐림, 2: 비, 3, 눈',
    `DISTANCE` int unsigned NOT NULL COMMENT '산책 거리',
    `WALKING_TIME` TIME NOT NULL COMMENT '산책 시간',
    `CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    `UPDATE_AT` DATETIME COMMENT '수정 시간',
    `MEMO` VARCHAR(255) NOT NULL COMMENT '메모',
    `WALKING_RECORD_IMAGE_URL` VARCHAR(255) NULL COMMENT '산책 기록 이미지 URL',
    FOREIGN KEY (`PET_PROFILE_ID`) REFERENCES `PET_PROFILE` (`PET_PROFILE_ID`)
);

CREATE TABLE `TODO` (
    `TODO_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '오늘할일ID 기본키',
    `USER_ID` int unsigned NOT NULL COMMENT '유저ID',
    `PREPARATION_CONTENT` VARCHAR(255) NOT NULL COMMENT '작성 내용',
    `CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    `UPDATE_AT` DATETIME COMMENT '수정 시간',
    FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
);

CREATE TABLE `CERTIFICATION_NUMBER` (
    `CERTIFICATION_NUMBER_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '인증ID 기본키',
    `CERT_TYPE` CHAR(1) NOT NULL COMMENT '0: 휴대폰 인증, 1: 이메일 인증',
    `EMAIL` VARCHAR(200) NOT NULL COMMENT '이메일',
    `PHONE` CHAR(11) NOT NULL COMMENT '휴대폰번호',
    `CART_NUM` CHAR(6) NOT NULL COMMENT '인증번호',
    `SEND_TIME` DATETIME NOT NULL COMMENT '발송 시간',
    `USER_ID` int unsigned COMMENT '회원정보가 없을 시에는 외래키를 가져올 수 없으므로 외래키로 잡지않았음'
);

CREATE TABLE `COMMUNITY` (
    `COMMUNITY_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '커뮤니티ID 기본키',
    `USER_ID` int unsigned NOT NULL COMMENT '유저ID',
    `COMM_CATE_NAME` ENUM('INTRO', 'BOARD', 'ROUTE', 'PHOTO') NOT NULL COMMENT '커뮤니티 카테고리 INTRO = 가입인사, BOARD = 자유게시판, ROUTE = 산책 경로, PHOTO = 강아지 사진',
    `LIKE_COUNT` int unsigned DEFAULT 0 NOT NULL COMMENT '좋아요 수',
    `CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    `UPDATE_AT` DATETIME COMMENT '수정 시간',
    `CONTENTS` VARCHAR(1000) NOT NULL COMMENT '내용',
    `THUMB_NAIL_IMG_URL` VARCHAR(255) NULL COMMENT '썸네일 이미지 URL',
    FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
);

CREATE TABLE `COMMUNITY_REPLY` (
    `COMMUNITY_REPLY_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '커뮤니티 댓글ID 기본키',
    `COMMUNITY_ID` int unsigned NOT NULL COMMENT '커뮤니티ID',
    `USER_ID` int unsigned NOT NULL COMMENT '유저ID',
    `PARENT_REPLY` CHAR(1) NOT NULL COMMENT '원댓글 여부 0: 원댓글, 1: 대댓글',
    `CONTENTS` VARCHAR(255) NOT NULL COMMENT '댓글 내용',
    `CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    FOREIGN KEY (`COMMUNITY_ID`) REFERENCES `COMMUNITY` (`COMMUNITY_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
);

CREATE TABLE `COMM_ATTACHMENT` (
    `COMM_ATTACHMENT_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '커뮤니티 첨부파일ID 기본키',
    `COMMUNITY_ID` int unsigned NOT NULL COMMENT '커뮤니티ID',
    `IMAGE_URL` VARCHAR(255) COMMENT '첨부 이미지 URL',
    `CREATE_AT` DATETIME NOT NULL COMMENT '생성 시간',
    FOREIGN KEY (`COMMUNITY_ID`) REFERENCES `COMMUNITY` (`COMMUNITY_ID`)
);

CREATE TABLE `ATTACHMENT` (
    `ATTACHMENT_ID` int unsigned PRIMARY KEY AUTO_INCREMENT COMMENT '문의 및 신고 첨부파일ID 기본키',
    `INQUERY_AND_REPORT_ID` int unsigned NOT NULL COMMENT '문의 및 신고ID',
    `INQUERY_AND_REPORT_CATE_CD_ID` int unsigned NOT NULL COMMENT '문의 및 신고 카테고리ID',
    `FILE_URL` VARCHAR(255) NULL COMMENT '파일 주소',
    `CREATE_AT` DATETIME NULL COMMENT '생성 시간',
    FOREIGN KEY (`INQUERY_AND_REPORT_ID`) REFERENCES `INQUERY_AND_REPORT` (`INQUERY_AND_REPORT_ID`),
    FOREIGN KEY (`INQUERY_AND_REPORT_CATE_CD_ID`) REFERENCES `INQUERY_AND_REPORT_CATE_CD` (`INQUERY_AND_REPORT_CATE_CD_ID`)
);

